### ISSUE TITLE
Apply page: add more info about the selection criteria

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#104]

**Comment by carletex** [comment]
Hey @escottalexander! Assigning this to you (I can't on the "Assignees" field so doing it here. I've just invited you to the BG org too).

As we discussed yesterday, let's have more info on the apply page so people are more aware of what we are looking for (and what we are NOT looking for). I think it shouldn't be a wall of text, but something concise. 

Let me know if you have any questions!!

(A bit related is #66 )
