### ISSUE TITLE
Private notes

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/grants.buidlguidl.com#113]
It's useful to have a private note field for admins.

We have to consider "security" implications. We don't want to leak the private notes. Maybe we can use firestore subcolletctions... or just not return that field from any query (except for the "admin review" one)

**To add the private note**

Maybe it can be on the "edit grant" modal

![image](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/ac276e39-7952-4aca-a990-6e69b8901a0d)

**To show the private note**

We can show it (in small text) below on the GrantReview (For proposed ones)

e.g.

![image](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/90dab8bf-c4ce-436b-a898-787c346a0962)

even with a diff color

![image](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/f97a366b-c2ad-4cb5-8be2-fc32a153f26f)

**Comment by andrealbiac** [comment]
To add some (unsolicited but maybe useful) feedback, I think to me it makes sense to show it in black, maybe even 75% opacity? Like a dark grey. I think in red looks a bit like an error message 

Also a little title like 'Notes' would be cool!

**Comment by andrealbiac** [comment]
Oh right! Okay sorry I misunderstood the feature, thought this was a note from the admins to the grant owner but it's just for admins! 
Then it makes sense that you want to highlight it as a warning & in red👌🏻

**Comment by carletex** [comment]
Sorry, I probably wasn't clear in the issue description (Since I talked about this before with Shiv).

I might send you some color options when the PR is ready tho.

Thanks!

**Comment by andrealbiac** [comment]
No worries! 

Okay cool 🙌🏻 no pressure though :) just here if you need me

**Comment by carletex** [comment]
Closed on #117
