### ISSUE TITLE
Featured grants image aspect ratios

### ISSUE THREAD

**Issue by andrealbiac** [BuidlGuidl/grants.buidlguidl.com#114]
Right now the thumbnails for Featured grants look squashed down

![photo_2024-04-17 15 13 50](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/fb4996e3-176c-4d4f-889e-e7b6db7757a3)

Gonna change the aspect ratio of these and see if that fixes the problem ✌🏻

**Comment by andrealbiac** [comment]
Dropping the new images here, also in the tg channel 🙌🏻

![bytes032 eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/7b4f31a7-5792-4ffe-bb39-52b10b13015f)
![erhant eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/e5c8f6fa-bb45-4473-97bf-f54a07b21966)
![jessys-hacker-house](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/44b73144-c3a2-4429-9c56-c530eedc0159)
![jtriley eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/61a7fa1e-cf4f-4881-8c9a-c65dbf906027)
![solidity-by-example](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/1c4a8fd0-fcd0-43a4-a2b4-0d64da84accc)
![w1nt3r-evm](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/9ae68ce5-ffd8-4581-8e6d-664332fe3967)

Not sure who should update these so mentioning both @technophile-04 & @Pabl0cks , thank you! <3

**Comment by Pabl0cks** [comment]
Thanks @andrealbiac for the assets! ❤

I just did a local test, here you can check how it looks with new images vs old images. 

<details>
<summary>(Don't know if it will be easy to appreciate the differences with this image)</summary>

![new-vs-old-featuredImages](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/55535804/7707045e-4357-45ed-86f5-8ff0ca1430a3)
</details>

Not sure if the squash down effect got solved, my eyes can't really tell! :) But some of the images are losing definition, noticiable specially in the ones having text. 

Let me know if you want to do another test with other assets 🙌

**Comment by andrealbiac** [comment]
Cool, thanks so much!

They definately look less squashed (maybe if you look at the little pfp circle you can tell the difference? haha), but yes maybe now they have the good ratio proportion but they're too small. 

Sending them here again a bit bigger ✌🏻 let's see if they look better now

![bytes032 eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/d5afb79c-a795-4a5d-a868-09457a9d928a)
![erhant eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/9289ca4c-df1e-4206-9954-59ffdb487b35)
![jessys-hacker-house](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/d36d58fb-c608-4ede-a6e9-165305f6f47c)
![jtriley eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/ee4ab5dd-204e-4b12-a0f2-4826549028a5)
![solidity-by-example](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/901c68e2-6a2f-47b1-88ac-1c34223609b0)
![w1nt3r-evm](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/82c4add8-8bef-44d4-b127-6092890477ea)

**Comment by Pabl0cks** [comment]
> They definately look less squashed (maybe if you look at the little pfp circle you can tell the difference? haha)

Ohh yes the pfp was def not a circle! :)

<details>
<summary>Here you can check with the new images. Do you see them OK or want to try with bigger images?</summary>

![new-vs-old-featuredImages](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/55535804/27ff85ab-b6f6-4109-83ec-1e5611131814)

</details>

**Comment by andrealbiac** [comment]
I can't tell the quality very well from the screenshots but I think they still look a bit small. I made them the same size that they're uploaded now so then there's no doubt it's gonna look okay 👌🏻

So these are the new pics (once and for all haha). Thanks so much!

![bytes032 eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/ed7bc184-6f3b-4139-a3cd-c98cddb808c1)
![erhant eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/6689b23d-9acc-45f4-bd3f-688be203cdc3)
![jessys-hacker-house](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/f6ff8b13-3948-4d33-8304-e674e445aa60)
![jtriley eth](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/2c593329-6c2f-44a3-bb01-63062e4abb29)
![solidity-by-example](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/53f24a78-b5ef-40d2-b94b-4192f9c3dd19)
![w1nt3r-evm](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/39b708a2-c5dc-4d22-ab2f-0bf65ccb6f0c)
