### ISSUE TITLE
Change grant status in database for oO4ZVdmkyLhd3YpE91U5

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#130]
Moved grant oO4ZVdmkyLhd3YpE91U5 to complete by mistake, thinking the 50% tx worked

I tried to do the 50% send tx, but didn't realize any error, and completed it with the captured tx hash. 
Somehow an error must have happend with the safe multisig tx sign and the tx didn't really happend, so completed it without sending funds.

Would need to change the status to "submitted" to do the 50% send and Complete actions again.

Owner of the grant: 0x981ab0D817710d8FFFC5693383C00D985A3BDa38
Grant id: oO4ZVdmkyLhd3YpE91U5
Wrong tx hash: 0x782d74693143622644f4b57c0403d39a996dec514ed488a2a795d77e5310ca51

**Comment by carletex** [comment]
Done! Changed the status + deleted the completedTx + completedTimestamp fields.
