### ISSUE TITLE
Manually update a couple of grants

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#139]
There are a couple of grants where we've sent the 100% of the grant with a direct transfer, and we should reflect it in their grant status:

Data update for grant `K1Dnwm4dyO5LUXIr5JYa`:
- Update quantity to: 0.75 eth
- Update txhash to: https://optimistic.etherscan.io/tx/0x5eb98ed817d400759eb08422ea8f81634f5fe7b36cf889bd215ca2850f570734
- Update grant status to: completed

Data update for grant `5r4t1KfuVjYHj6Yt1u23`:
- Update grant status to: completed

No hurry, just creating the issue to update them at some point.

**Comment by carletex** [comment]
Updated both! Let me know if it shows correctly.

PS. Both had approved TX... I just duplicated the tx hash for completedTx too. It show 50% / 50 % and it point to the same TX... I think it should be fine.

**Comment by Pabl0cks** [comment]
They both look great! TYSM 🙏
