### ISSUE TITLE
Review font-size consistency between titles

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#28]
- **Hero**: `text-3xl md:text-4xl lg:text-6xl lg:leading-[1.2] text-center lg:text-left font-ppEditorial`
- **Community grants**: `text-3xl sm:text-4xl lg:text-5xl text-center lg:text-left font-ppEditorial`
- **Completed grants**: `text-3xl md:text-4xl lg:text-6xl text-center lg:text-left font-ppEditorial`

Maybe it was a build decision, if not we could change Community grants title to: `text-3xl md:text-4xl lg:text-6xl text-center lg:text-left font-ppEditorial`. The problem seems to be in the current 1024 to 1280px width, where increasing the size makes the button to apply dissapear, we could lower the size for that resolution a bit (to all of them or only to Community grants)

**Comment by technophile-04** [comment]
I think it was tackled in #62 nicely, but we can create another issues if we find some more inconsistency 🙌
