### ISSUE TITLE
Load batch 0 and batch 1 final projects as completed grants

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#29]
Create a json file with all batch 0 and batch 1 projects to load them as completed grants. 

If any of the final projects is still pending to finish we could load it as "approved" (to confirm).

**Comment by carletex** [comment]
Check the https://github.com/BuidlGuidl/grants.buidlguidl.com/blob/main/packages/local_db/seed.sample.json file for reference on the «grant» collection.

More info about the schema here too: https://github.com/BuidlGuidl/grants.buidlguidl.com/blob/main/packages/nextjs/services/database/schema.ts#L41

**Comment by Pabl0cks** [comment]
I think I got the grants from batch 0 and 1 ready to load in the seed file (will create PR tomorrow morning).

Got doubts with 3 of them from Batch 1, **can delete them from the seed file and add them in the future**:
- 2 builds which are not in the builder profile yet (builders 0x4f099cFbC4043e60c52EF47EBC593ba0Bda5C85e and 0x4d639cbbc15fE5DB467dbF158a78a5Fa3Ac20877)
- 1 build seems WIP from the info in his build  (builder 0xF51cFA5eb9128F064eafb75524502A039F063D91)

Different case, **I guess we can ignore**, is not in the seed file:
- 1 builder from batch 1 has not submission in the Spreadsheet nor on his builder profile (nkbkd.eth - 0xDE5c8eAFEBEC017D9d26F757B9d7F04A0C1eb177)

I could delete them from the seed file and add them in the future.
