### ISSUE TITLE
Set initial metadata (title, description, thumbnail)

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#31]
Update generic SE-2 metadata from `app/layout.tsx` with an initial version for grants.

Here are the available thumbnails, we'll need to choose between dark and light:

| Light| Dark| 
| ------- | ----- | 
|  ![thumbnail-light](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/55535804/cf3b0f6d-2d1f-40ab-a512-6d21feec9e8f)  | ![thumbnail-dark](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/55535804/7c12747e-4050-4ffa-b884-d29cfa7c69dd) |

**Comment by carletex** [comment]
I asked Andrea for a thumbnail too

**Comment by carletex** [comment]
I think we also need to convey the "ecosystem" (bigger) grants. 

The title could be just "BuidlGuidl Grants"... and not sure about the description haha Just asked some people in the BG that are good with copy.
