### ISSUE TITLE
Completed grants needs a carousel or multiple rows

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#36]
Testing the initial grants data load I've realized we're missing the carousel, right now everything appears in 1 row.

We could add a carousel like in figma design, or start with a simple multiple rows and then iterate to a carousel. What do you think?

**Comment by carletex** [comment]
Yep, I see two options:

1. 1 row Carousel
2. Show 2 rows + button "view all" that goes to a /completed-grants page.

We might need the button anyway?

For the "featured grants" we have the same issue (we'll have more). So I guess it depends how much weight do we want to put on them.

**Comment by Pabl0cks** [comment]
> We might need the button anyway?

I believe so. 

**Completed grants** is going to be so big that probably the carousel doesn't even make sense, so maybe 1 or 2 rows and a button or underlined link "See all completed grants (19)"

For **Featured grants** size carousel may make sense, but perhaps for simplicity we can have the same approach that we implement on **Completed grants**.
