### ISSUE TITLE
Review stats logic

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#41]
Checking stats after initial grants data load, numbers felt a bit strange. I think we're showing completedGrants as Total Grants.

Creating this issue to discuss about the stats to set a initial logic for the section.

- **Total Grants**. I think we should show completed + approved in this stat. Right now is just counting completed.
- **Submissions**. As we were discussing in TG, I agree we could delete the stat since submissions are only open to BG members, and probably many of them will end up being approved, maybe after some iterations of the submission (managed in TG)
- **ETH Granted**. Should we save this stat in the grants data and query to it? Right now we are showing the sum of askAmount for completed grants. This stat could be updated after we transfer the grant amount.
- **Active Grants**. I think this one is fine as it is

Should we maybe change "Submissions" for "Completed Grants"? Or delete "Submissions" and show "Completed Grants" and "Active Grants" and people may not need "Total Grants" stat? Just thinking out loud

**Comment by technophile-04** [comment]
Tysm @Pabl0cks, agree with all the pointers and created a #42 for it, something Carlos as discussed.

> ETH Granted. Should we save this stat in the grants data and query to it? Right now we are showing the sum of askAmount for completed grants. This stat could be updated after we transfer the grant amount.

I think `askAmount` is something that is something going to be changed in the future. Currently, the assumption is ETHGranted == askAmount. But yup maybe we should add a field `ethGranted` to `grants` schema

So,
`askAmount` => The amount builder selected while submitting new grant proposal
`ethGranted` => This will change two times in the lifecycle of the grant : 
             1. When admins mark grant as "approved" and sends 50%* of askAmount* 
             2. When admins mark grant as "completed" and sends rest 50%* of askAmount*
                             
  

But cc @carletex and would love to hear his thoughts  🙌

**Comment by carletex** [comment]
#42
