### ISSUE TITLE
Review spacing across the landing

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#47]
Everything feels a bit too tight, we could add a bit more spacing between different sections and between the different parts of each section.

![image](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/55535804/1a01c57d-f539-48bc-9605-dd1c4b14bdd0)

**Comment by andrealbiac** [comment]
I agree, think almost everything could use a bit more spacing. Sharing some other examples that I've seen here: basically around the titles of sections & the margin of the cards.

<img width="1288" alt="Captura de pantalla 2024-03-04 a las 17 41 08" src="https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/2a3ea2ad-2070-4d09-b46f-c1a8bc23f6bf">
<img width="1438" alt="Captura de pantalla 2024-03-04 a las 17 41 24" src="https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/6c1b87c9-eaac-4a7e-85b1-6f70b475bd24">


Also, not sure this is the best Issue to mention this or it should be in #28 , but I would also reduce the font sizes on:
- card titles
- card paragraph
- community grants cta section paragraph (& make it equal to the hero paragraph)
- all section titles (maybe except the hero) and make it equal to CTA section (that one looks okay to me)
- 'see completed grants' button 

I can provide more specific details about this if needed, thanks so much guys!! :)
