### ISSUE TITLE
Builders Addresses should point to their BG profile

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/grants.buidlguidl.com#48]
In completed grants & active grants:

![image](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/b6309484-3c30-469e-a4b1-d3b7f3c164ab)

I believe we want the links to point to their BG profile, as in `packages/nextjs/app/admin/_components/GrantReview.tsx.

If we want to extract the functionality, maybe we can add a prop to `Address`.

What do you guys think?

@technophile-04 @Pabl0cks

**Comment by technophile-04** [comment]
Yup it was going in my mind since #43, will create a PR with prop to `Address` 🙌
