### ISSUE TITLE
Review spacing in some edge case resolutions (1024px to 1300ish px width)

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#63]
Probably fixing from 1024px to 1280px (`lg` breakpoint) may be enough if next breakpoint makes it look worse in bigger resolutions from the `xl` breakpoint.

<details>
<summary>1280px example</summary>

![grants-1280width-small](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/55535804/bb361f4b-d0bb-4f0d-9df3-e1bdc5b478cc)

</details>

**Comment by carletex** [comment]
Is it only for "completed grants"?

**Comment by Pabl0cks** [comment]
> Is it only for "completed grants"?

Yep! Maybe other sections could have a little more spacing but not sure if they would look better or worse. So we can just set "completed grants" like they other ones and it would look balanced.

**Comment by carletex** [comment]
Should be fixed at #84 

leave this open until test (I yoloed the PR)

**Comment by Pabl0cks** [comment]
> Should be fixed at https://github.com/BuidlGuidl/grants.buidlguidl.com/pull/84

I see it great now! TYSM! Closing 🙌
