### ISSUE TITLE
Add a visual element to Community Grants section to show extra info depending on user status 

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#66]
Similar to what we're doing in SRE showing "Quest" to open challenges or "Locked" + icon with tooltip to closed challenges based on your builder status, we want to show extra info to:

- **Wallet not connected**: Ask the user to connect the wallet in order to check if he's in the BuidlGuidl or not, explaining he needs to be in BG to apply for a grant.
- **Wallet connected but not a BG member**: Suggest the user to make SRE in order to join BG and be able to apply for grants.
- **Wallet connected, BG member**: Explain that he can apply for grants because he is a BG member.

This has to be very visual and accomplish 2 main goals, drive non BG users to join BG through SRE, and make it more obvious that is a perk only to BG members.

For the logic, we'll just need to migrate it from `/apply` page ("Submit button") to the Community Grants section.

<details>
<summary>Here is the SRE button example</summary>

![image](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/55535804/8c440ed9-1324-463c-bbdc-ccf633a0552a)

</details>

**Comment by carletex** [comment]
A random idea (to make it more ceremonious)

> Wallet not connected: Ask the user to connect the wallet in order to check if he's in the BuidlGuidl or not, explaining he needs to be in BG to apply for a grant.

Show as Pablo is saying (:grey_question:  with tooltip saying connect your wallet) 

> Wallet connected, BG member: Explain that he can apply for grants because he is a BG member.

:heavy_check_mark: Wallet connected
:x: Not a BG member (:grey_question:  + tooltip: SRE, etc, etc)

To make it more ceremonious for the members, we could even show below the button something like:

:heavy_check_mark: Wallet connected
:heavy_check_mark: BG member

**Comment by carletex** [comment]
@andrealbiac gave us this for us to implement. Thanks!! <3

(let's forget about the confetti for now :D)

[Figma](https://www.figma.com/file/4fGecjQWzslAgnFDVsmoiF/BG-Grants?type=design&node-id=547-20&mode=design&t=vucgapyduATupoiU-0)

![1](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/a58ec008-8e33-4b9d-9447-71965e2cbe26)
![2](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/0d13ddd6-2b9e-4929-9c5c-1e1272bc81fc)
![3](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/63509ced-a61d-4c8e-b48e-6ad3f1a31c17)
