### ISSUE TITLE
Let admins manage impact grants

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#70]
Impact grants are going to grow, funding more key players in the ecosystem. Austin wants to be able to add new Impact grants directly from the Admin panel (they won't have an approval workflow). 

The workflow is something like this:
- Austin offers the grant, if accepted he asks the grantee for a 1-2 liner description.
- In the admin panel he sets up the grant, introducing the title, description and image, and sets the grant amount.

Initially we can start by registering the grant amount he manually sent to the grantee with the grant wallet, and not register any hash?

**Comment by Belloabraham121** [comment]
Has anybody worked on this?

**Comment by Pabl0cks** [comment]
> Has anybody worked on this?

We haven't needed this yet, most of these cases are simply coming through normal grant applications, so we will close this issue for now. 🙏
