### ISSUE TITLE
Better images for new ecosystem grants

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/grants.buidlguidl.com#87]
Austin added 3 more ecosystem grants here #86 

![image](https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/2486142/6ac144f4-f1bf-4806-941b-179d2a55132f)

Lets create better image for those, more aligned with the other ones. cc @andrealbiac

**Comment by andrealbiac** [comment]
New cover images (uploaded to the Telegram channel). 👉🏻 Need to change text color to white. Thanks guys!

<img width="782" alt="Captura de pantalla 2024-03-22 a las 16 22 00" src="https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/137904915/82c0f1f1-84d2-41f5-b113-1cb74a49459c">

**Comment by carletex** [comment]
Re-opening this until we change the images in the repo!
