### ISSUE TITLE
Grammar Fixes

### ISSUE THREAD

**Issue by sfaber34** [BuidlGuidl/grants.buidlguidl.com#91]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Anything else?

There is an opportunity to improve grammar in CommunityGrant.tsx and HomepageHero.tsx

**Comment by carletex** [comment]
Fixed on #92
