### ISSUE TITLE
Handful of suggestions

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/grants.buidlguidl.com#98]
All of these can be vetoed if it doesn't make sense but I think it would be nice to have the following features for admins:

- Notes area next to each application where an admin can write down their thoughts about a project. (bonus points if there is some way to tell which admin left the note in case collaboration is required)
- Apply custom tags to an application ( [contacted], [5-star], [high-impact] ... )
- Show the date a grant was submitted
- Sort by user tags, application tags or dates

All of the sorting/tagging features are not really high priority at the moment but if we have an influx of applications then they will be vital. The notes feature would be pretty handy at any point.

**Comment by carletex** [comment]
Hey @escottalexander thanks for suggestions!

> Show the date a grant was submitted

Yep, this is a must-have. Will make a PR soon.

---

The other stuff: IMO it's a bit early to build these kinds of things. From past experiences, it might be better to play more with the tool and also see what the influx looks like in a regular basis (now we just launched and we haven't approved any grants, so the list is big!).

What do you think if:
- For now, let's copy/paste this into a _shared_ spreadsheet/notion, where we can add notes, tags, etc.
- In a couple of months:
    a. This is still a PITA => let's build some of these things into the tool
    b. We don't even use the spreadsheet anymore (i.e. there are only a few to review per week)
- (ofc if there is something pretty obvious that we need... let's tackle it right now!)

We have followed this process for the BG app and I think it's been working out. We've built some stuff into the BG app, and some other things (that we thought as  _important_ at the beginning) we haven't. Small iterations are the way to go!

Nothing wrong with the suggestions tho, I think they are great. This comes from not wanting to early-optimize and being efficient with our resources.

**Comment by carletex** [comment]
Created https://github.com/BuidlGuidl/grants.buidlguidl.com/pull/99

**Comment by escottalexander** [comment]
Sounds good! Agree totally that we shouldn't over-optimize it too early.
